xml: avoid ClassCastException exception
`iso8601` expects a DateTime object and cannot be called with a string.

   java.lang.ClassCastException: java.lang.String cannot be cast to
      org.joda.time.ReadableInstant